/* tslint:disable */
/* eslint-disable */
/**
 * CS-QUIZ 프로젝트 API 명세서
 * quiz api 명세서
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CotatoPolicyInfoResponse } from './cotato-policy-info-response';

/**
 * 
 * @export
 * @interface CotatoFindMemberPolicyResponse
 */
export interface CotatoFindMemberPolicyResponse {
    /**
     * 
     * @type {number}
     * @memberof CotatoFindMemberPolicyResponse
     */
    'memberId'?: number;
    /**
     * 회원이 체크하지 않은 필수 정책 목록
     * @type {Array<CotatoPolicyInfoResponse>}
     * @memberof CotatoFindMemberPolicyResponse
     */
    'essentialPolicies'?: Array<CotatoPolicyInfoResponse>;
    /**
     * 회원이 체크하지 않은 선택 정책 목록
     * @type {Array<CotatoPolicyInfoResponse>}
     * @memberof CotatoFindMemberPolicyResponse
     */
    'optionalPolicies'?: Array<CotatoPolicyInfoResponse>;
}

