/* tslint:disable */
/* eslint-disable */
/**
 * CS-QUIZ 프로젝트 API 명세서
 * quiz api 명세서
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CotatoMemberMyPageInfoResponse
 */
export interface CotatoMemberMyPageInfoResponse {
    /**
     * 
     * @type {number}
     * @memberof CotatoMemberMyPageInfoResponse
     */
    'memberId'?: number;
    /**
     * 
     * @type {string}
     * @memberof CotatoMemberMyPageInfoResponse
     */
    'email'?: string;
    /**
     * 
     * @type {string}
     * @memberof CotatoMemberMyPageInfoResponse
     */
    'name'?: string;
    /**
     * 
     * @type {number}
     * @memberof CotatoMemberMyPageInfoResponse
     */
    'generationNumber'?: number;
    /**
     * 
     * @type {string}
     * @memberof CotatoMemberMyPageInfoResponse
     */
    'position'?: CotatoMemberMyPageInfoResponsePositionEnum;
    /**
     * 
     * @type {string}
     * @memberof CotatoMemberMyPageInfoResponse
     */
    'phoneNumber'?: string;
    /**
     * 
     * @type {string}
     * @memberof CotatoMemberMyPageInfoResponse
     */
    'profileImage'?: string;
}

export const CotatoMemberMyPageInfoResponsePositionEnum = {
    None: 'NONE',
    Be: 'BE',
    Fe: 'FE',
    Design: 'DESIGN',
    Pm: 'PM'
} as const;

export type CotatoMemberMyPageInfoResponsePositionEnum = typeof CotatoMemberMyPageInfoResponsePositionEnum[keyof typeof CotatoMemberMyPageInfoResponsePositionEnum];


