/* tslint:disable */
/* eslint-disable */
/**
 * CS-QUIZ 프로젝트 API 명세서
 * quiz api 명세서
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CotatoRecordResponse } from './cotato-record-response';
// May contain unused imports in some cases
// @ts-ignore
import type { CotatoScorerResponse } from './cotato-scorer-response';

/**
 * 
 * @export
 * @interface CotatoRecordsAndScorerResponse
 */
export interface CotatoRecordsAndScorerResponse {
    /**
     * 
     * @type {Array<CotatoRecordResponse>}
     * @memberof CotatoRecordsAndScorerResponse
     */
    'records'?: Array<CotatoRecordResponse>;
    /**
     * 
     * @type {CotatoScorerResponse}
     * @memberof CotatoRecordsAndScorerResponse
     */
    'scorer'?: CotatoScorerResponse;
}

