/* tslint:disable */
/* eslint-disable */
/**
 * CS-QUIZ 프로젝트 API 명세서
 * quiz api 명세서
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CotatoLocalTime
 */
export interface CotatoLocalTime {
    /**
     * 
     * @type {number}
     * @memberof CotatoLocalTime
     */
    'hour'?: number;
    /**
     * 
     * @type {number}
     * @memberof CotatoLocalTime
     */
    'minute'?: number;
    /**
     * 
     * @type {number}
     * @memberof CotatoLocalTime
     */
    'second'?: number;
    /**
     * 
     * @type {number}
     * @memberof CotatoLocalTime
     */
    'nano'?: number;
}

