/* tslint:disable */
/* eslint-disable */
/**
 * CS-QUIZ 프로젝트 API 명세서
 * quiz api 명세서
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CotatoCreateChoiceRequest } from './cotato-create-choice-request';

/**
 * 
 * @export
 * @interface CotatoCreateMultipleQuizRequest
 */
export interface CotatoCreateMultipleQuizRequest {
    /**
     * 
     * @type {number}
     * @memberof CotatoCreateMultipleQuizRequest
     */
    'number'?: number;
    /**
     * 
     * @type {string}
     * @memberof CotatoCreateMultipleQuizRequest
     */
    'question'?: string;
    /**
     * 
     * @type {File}
     * @memberof CotatoCreateMultipleQuizRequest
     */
    'image'?: File;
    /**
     * 
     * @type {Array<CotatoCreateChoiceRequest>}
     * @memberof CotatoCreateMultipleQuizRequest
     */
    'choices'?: Array<CotatoCreateChoiceRequest>;
}

