/* tslint:disable */
/* eslint-disable */
/**
 * CS-QUIZ 프로젝트 API 명세서
 * quiz api 명세서
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CotatoChoiceResponse } from './cotato-choice-response';

/**
 * 
 * @export
 * @interface CotatoMultipleQuizResponse
 */
export interface CotatoMultipleQuizResponse {
    /**
     * 
     * @type {number}
     * @memberof CotatoMultipleQuizResponse
     */
    'id'?: number;
    /**
     * 
     * @type {number}
     * @memberof CotatoMultipleQuizResponse
     */
    'number'?: number;
    /**
     * 
     * @type {string}
     * @memberof CotatoMultipleQuizResponse
     */
    'question'?: string;
    /**
     * 
     * @type {string}
     * @memberof CotatoMultipleQuizResponse
     */
    'image'?: string;
    /**
     * 
     * @type {Array<CotatoChoiceResponse>}
     * @memberof CotatoMultipleQuizResponse
     */
    'choices'?: Array<CotatoChoiceResponse>;
}

