/* tslint:disable */
/* eslint-disable */
/**
 * CS-QUIZ 프로젝트 API 명세서
 * quiz api 명세서
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CotatoUpdateSessionPhotoOrderInfoRequest } from './cotato-update-session-photo-order-info-request';

/**
 * 
 * @export
 * @interface CotatoUpdateSessionPhotoOrderRequest
 */
export interface CotatoUpdateSessionPhotoOrderRequest {
    /**
     * 
     * @type {number}
     * @memberof CotatoUpdateSessionPhotoOrderRequest
     */
    'sessionId'?: number;
    /**
     * 
     * @type {Array<CotatoUpdateSessionPhotoOrderInfoRequest>}
     * @memberof CotatoUpdateSessionPhotoOrderRequest
     */
    'orderInfos'?: Array<CotatoUpdateSessionPhotoOrderInfoRequest>;
}

