/* tslint:disable */
/* eslint-disable */
/**
 * CS-QUIZ 프로젝트 API 명세서
 * quiz api 명세서
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CotatoCreateShortAnswerRequest } from './cotato-create-short-answer-request';

/**
 * 
 * @export
 * @interface CotatoCreateShortQuizRequest
 */
export interface CotatoCreateShortQuizRequest {
    /**
     * 
     * @type {number}
     * @memberof CotatoCreateShortQuizRequest
     */
    'number'?: number;
    /**
     * 
     * @type {string}
     * @memberof CotatoCreateShortQuizRequest
     */
    'question'?: string;
    /**
     * 
     * @type {File}
     * @memberof CotatoCreateShortQuizRequest
     */
    'image'?: File;
    /**
     * 
     * @type {Array<CotatoCreateShortAnswerRequest>}
     * @memberof CotatoCreateShortQuizRequest
     */
    'shortAnswers'?: Array<CotatoCreateShortAnswerRequest>;
}

