/* tslint:disable */
/* eslint-disable */
/**
 * CS-QUIZ 프로젝트 API 명세서
 * quiz api 명세서
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CotatoWinnerInfoResponse
 */
export interface CotatoWinnerInfoResponse {
    /**
     * 
     * @type {number}
     * @memberof CotatoWinnerInfoResponse
     */
    'memberId'?: number;
    /**
     * 
     * @type {string}
     * @memberof CotatoWinnerInfoResponse
     */
    'memberName'?: string;
    /**
     * 
     * @type {number}
     * @memberof CotatoWinnerInfoResponse
     */
    'educationId'?: number;
    /**
     * 
     * @type {string}
     * @memberof CotatoWinnerInfoResponse
     */
    'backFourNumber'?: string;
    /**
     * 
     * @type {string}
     * @memberof CotatoWinnerInfoResponse
     */
    'memberPosition'?: CotatoWinnerInfoResponseMemberPositionEnum;
}

export const CotatoWinnerInfoResponseMemberPositionEnum = {
    None: 'NONE',
    Be: 'BE',
    Fe: 'FE',
    Design: 'DESIGN',
    Pm: 'PM'
} as const;

export type CotatoWinnerInfoResponseMemberPositionEnum = typeof CotatoWinnerInfoResponseMemberPositionEnum[keyof typeof CotatoWinnerInfoResponseMemberPositionEnum];


