/* tslint:disable */
/* eslint-disable */
/**
 * CS-QUIZ 프로젝트 API 명세서
 * quiz api 명세서
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CotatoHallOfFameInfo
 */
export interface CotatoHallOfFameInfo {
    /**
     * 
     * @type {number}
     * @memberof CotatoHallOfFameInfo
     */
    'memberId'?: number;
    /**
     * 
     * @type {string}
     * @memberof CotatoHallOfFameInfo
     */
    'name'?: string;
    /**
     * 
     * @type {number}
     * @memberof CotatoHallOfFameInfo
     */
    'count'?: number;
}

