/* tslint:disable */
/* eslint-disable */
/**
 * CS-QUIZ 프로젝트 API 명세서
 * quiz api 명세서
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CotatoSessionListPhotoInfoResponse
 */
export interface CotatoSessionListPhotoInfoResponse {
    /**
     * 
     * @type {number}
     * @memberof CotatoSessionListPhotoInfoResponse
     */
    'photoId'?: number;
    /**
     * 
     * @type {string}
     * @memberof CotatoSessionListPhotoInfoResponse
     */
    'photoUrl'?: string;
    /**
     * 
     * @type {number}
     * @memberof CotatoSessionListPhotoInfoResponse
     */
    'order'?: number;
}

