/* tslint:disable */
/* eslint-disable */
/**
 * CS-QUIZ 프로젝트 API 명세서
 * quiz api 명세서
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CotatoPolicyInfoResponse
 */
export interface CotatoPolicyInfoResponse {
    /**
     * 정책 PK
     * @type {number}
     * @memberof CotatoPolicyInfoResponse
     */
    'policyId'?: number;
    /**
     * 필수 동의 항목 여부
     * @type {string}
     * @memberof CotatoPolicyInfoResponse
     */
    'type'?: CotatoPolicyInfoResponseTypeEnum;
    /**
     * 정책 타이틀
     * @type {string}
     * @memberof CotatoPolicyInfoResponse
     */
    'title'?: string;
    /**
     * 정책 내용 게시글
     * @type {string}
     * @memberof CotatoPolicyInfoResponse
     */
    'content'?: string;
}

export const CotatoPolicyInfoResponseTypeEnum = {
    Essential: 'ESSENTIAL',
    Optional: 'OPTIONAL'
} as const;

export type CotatoPolicyInfoResponseTypeEnum = typeof CotatoPolicyInfoResponseTypeEnum[keyof typeof CotatoPolicyInfoResponseTypeEnum];


