/* tslint:disable */
/* eslint-disable */
/**
 * CS-QUIZ 프로젝트 API 명세서
 * quiz api 명세서
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CotatoRecordResponse
 */
export interface CotatoRecordResponse {
    /**
     * 
     * @type {number}
     * @memberof CotatoRecordResponse
     */
    'recordId'?: number;
    /**
     * 
     * @type {number}
     * @memberof CotatoRecordResponse
     */
    'ticketNumber'?: number;
    /**
     * 
     * @type {number}
     * @memberof CotatoRecordResponse
     */
    'memberId'?: number;
    /**
     * 
     * @type {string}
     * @memberof CotatoRecordResponse
     */
    'memberName'?: string;
    /**
     * 
     * @type {string}
     * @memberof CotatoRecordResponse
     */
    'backFourNumber'?: string;
    /**
     * 
     * @type {string}
     * @memberof CotatoRecordResponse
     */
    'reply'?: string;
}

