/* tslint:disable */
/* eslint-disable */
/**
 * CS-QUIZ 프로젝트 API 명세서
 * quiz api 명세서
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CotatoReplyRequest
 */
export interface CotatoReplyRequest {
    /**
     * 
     * @type {number}
     * @memberof CotatoReplyRequest
     */
    'quizId': number;
    /**
     * 
     * @type {number}
     * @memberof CotatoReplyRequest
     */
    'memberId': number;
    /**
     * 
     * @type {Array<string>}
     * @memberof CotatoReplyRequest
     */
    'inputs': Array<string>;
}

