/* tslint:disable */
/* eslint-disable */
/**
 * CS-QUIZ 프로젝트 API 명세서
 * quiz api 명세서
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CotatoCreateChoiceRequest
 */
export interface CotatoCreateChoiceRequest {
    /**
     * 
     * @type {string}
     * @memberof CotatoCreateChoiceRequest
     */
    'content'?: string;
    /**
     * 
     * @type {number}
     * @memberof CotatoCreateChoiceRequest
     */
    'number'?: number;
    /**
     * 
     * @type {string}
     * @memberof CotatoCreateChoiceRequest
     */
    'isAnswer'?: CotatoCreateChoiceRequestIsAnswerEnum;
}

export const CotatoCreateChoiceRequestIsAnswerEnum = {
    Answer: 'ANSWER',
    NoAnswer: 'NO_ANSWER',
    Secret: 'SECRET'
} as const;

export type CotatoCreateChoiceRequestIsAnswerEnum = typeof CotatoCreateChoiceRequestIsAnswerEnum[keyof typeof CotatoCreateChoiceRequestIsAnswerEnum];


