/* tslint:disable */
/* eslint-disable */
/**
 * CS-QUIZ 프로젝트 API 명세서
 * quiz api 명세서
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { CotatoAddSessionImageResponse } from '../model';
// @ts-ignore
import type { CotatoAddSessionResponse } from '../model';
// @ts-ignore
import type { CotatoCsEducationOnSessionNumberResponse } from '../model';
// @ts-ignore
import type { CotatoDeleteSessionImageRequest } from '../model';
// @ts-ignore
import type { CotatoLocalTime } from '../model';
// @ts-ignore
import type { CotatoSessionListResponse } from '../model';
// @ts-ignore
import type { CotatoUpdateSessionImageOrderRequest } from '../model';
// @ts-ignore
import type { CotatoUpdateSessionNumberRequest } from '../model';
// @ts-ignore
import type { CotatoUpdateSessionRequest } from '../model';
/**
 * SessionControllerApi - axios parameter creator
 * @export
 */
export const SessionControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 세션 추가하기
         * @summary Session 추가하기
         * @param {number} generationId 
         * @param {string} title 
         * @param {string} description 
         * @param {string} sessionDate 
         * @param {Array<File>} [images] 
         * @param {number} [latitude] 
         * @param {number} [longitude] 
         * @param {string} [placeName] 
         * @param {CotatoLocalTime} [attendanceDeadLine] 
         * @param {CotatoLocalTime} [lateDeadLine] 
         * @param {AddSessionItIssueEnum} [itIssue] 
         * @param {AddSessionNetworkingEnum} [networking] 
         * @param {AddSessionCsEducationEnum} [csEducation] 
         * @param {AddSessionDevTalkEnum} [devTalk] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addSession: async (generationId: number, title: string, description: string, sessionDate: string, images?: Array<File>, latitude?: number, longitude?: number, placeName?: string, attendanceDeadLine?: CotatoLocalTime, lateDeadLine?: CotatoLocalTime, itIssue?: AddSessionItIssueEnum, networking?: AddSessionNetworkingEnum, csEducation?: AddSessionCsEducationEnum, devTalk?: AddSessionDevTalkEnum, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'generationId' is not null or undefined
            assertParamExists('addSession', 'generationId', generationId)
            // verify required parameter 'title' is not null or undefined
            assertParamExists('addSession', 'title', title)
            // verify required parameter 'description' is not null or undefined
            assertParamExists('addSession', 'description', description)
            // verify required parameter 'sessionDate' is not null or undefined
            assertParamExists('addSession', 'sessionDate', sessionDate)
            const localVarPath = `/v1/api/session/add`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new ((configuration && configuration.formDataCtor) || FormData)();

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


            if (generationId !== undefined) { 
                localVarFormParams.append('generationId', generationId as any);
            }
                if (images) {
                images.forEach((element) => {
                  localVarFormParams.append('images', element as any);
                })
            }

    
            if (title !== undefined) { 
                localVarFormParams.append('title', title as any);
            }
    
            if (description !== undefined) { 
                localVarFormParams.append('description', description as any);
            }
    
            if (latitude !== undefined) { 
                localVarFormParams.append('latitude', latitude as any);
            }
    
            if (longitude !== undefined) { 
                localVarFormParams.append('longitude', longitude as any);
            }
    
            if (placeName !== undefined) { 
                localVarFormParams.append('placeName', placeName as any);
            }
    
            if (sessionDate !== undefined) { 
                localVarFormParams.append('sessionDate', sessionDate as any);
            }
    
            if (attendanceDeadLine !== undefined) { 
                localVarFormParams.append('attendanceDeadLine', new Blob([JSON.stringify(attendanceDeadLine)], { type: "application/json", }));
            }
    
            if (lateDeadLine !== undefined) { 
                localVarFormParams.append('lateDeadLine', new Blob([JSON.stringify(lateDeadLine)], { type: "application/json", }));
            }
    
            if (itIssue !== undefined) { 
                localVarFormParams.append('itIssue', itIssue as any);
            }
    
            if (networking !== undefined) { 
                localVarFormParams.append('networking', networking as any);
            }
    
            if (csEducation !== undefined) { 
                localVarFormParams.append('csEducation', csEducation as any);
            }
    
            if (devTalk !== undefined) { 
                localVarFormParams.append('devTalk', devTalk as any);
            }
    
    
            localVarHeaderParameter['Content-Type'] = 'multipart/form-data';
    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = localVarFormParams;

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 세션 수정 시 사진 추가하기, photoId 반환
         * @summary Session 수정 - 사진 추가하기
         * @param {number} sessionId 
         * @param {File} image 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        additionalSessionImage: async (sessionId: number, image: File, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'sessionId' is not null or undefined
            assertParamExists('additionalSessionImage', 'sessionId', sessionId)
            // verify required parameter 'image' is not null or undefined
            assertParamExists('additionalSessionImage', 'image', image)
            const localVarPath = `/v1/api/session/image`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new ((configuration && configuration.formDataCtor) || FormData)();

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


            if (sessionId !== undefined) { 
                localVarFormParams.append('sessionId', sessionId as any);
            }
    
            if (image !== undefined) { 
                localVarFormParams.append('image', image as any);
            }
    
    
            localVarHeaderParameter['Content-Type'] = 'multipart/form-data';
    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = localVarFormParams;

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 사진 삭제하기
         * @summary Session 수정 - 사진 삭제하기
         * @param {CotatoDeleteSessionImageRequest} cotatoDeleteSessionImageRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteSessionImage: async (cotatoDeleteSessionImageRequest: CotatoDeleteSessionImageRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'cotatoDeleteSessionImageRequest' is not null or undefined
            assertParamExists('deleteSessionImage', 'cotatoDeleteSessionImageRequest', cotatoDeleteSessionImageRequest)
            const localVarPath = `/v1/api/session/image`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(cotatoDeleteSessionImageRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} generationId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        findAllCsOnSessionsByGenerationId: async (generationId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'generationId' is not null or undefined
            assertParamExists('findAllCsOnSessionsByGenerationId', 'generationId', generationId)
            const localVarPath = `/v1/api/session/cs-on`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (generationId !== undefined) {
                localVarQueryParameter['generationId'] = generationId;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get Session Infos
         * @summary Session 리스트 정보 얻기
         * @param {number} generationId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        findSessionsByGenerationId: async (generationId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'generationId' is not null or undefined
            assertParamExists('findSessionsByGenerationId', 'generationId', generationId)
            const localVarPath = `/v1/api/session`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (generationId !== undefined) {
                localVarQueryParameter['generationId'] = generationId;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {CotatoUpdateSessionRequest} cotatoUpdateSessionRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateSession: async (cotatoUpdateSessionRequest: CotatoUpdateSessionRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'cotatoUpdateSessionRequest' is not null or undefined
            assertParamExists('updateSession', 'cotatoUpdateSessionRequest', cotatoUpdateSessionRequest)
            const localVarPath = `/v1/api/session/update`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(cotatoUpdateSessionRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 세션 사진 순서 바꾸기
         * @summary Session 수정 - 사진 순서
         * @param {CotatoUpdateSessionImageOrderRequest} cotatoUpdateSessionImageOrderRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateSessionImageOrder: async (cotatoUpdateSessionImageOrderRequest: CotatoUpdateSessionImageOrderRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'cotatoUpdateSessionImageOrderRequest' is not null or undefined
            assertParamExists('updateSessionImageOrder', 'cotatoUpdateSessionImageOrderRequest', cotatoUpdateSessionImageOrderRequest)
            const localVarPath = `/v1/api/session/image/order`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(cotatoUpdateSessionImageOrderRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {CotatoUpdateSessionNumberRequest} cotatoUpdateSessionNumberRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateSessionNumber: async (cotatoUpdateSessionNumberRequest: CotatoUpdateSessionNumberRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'cotatoUpdateSessionNumberRequest' is not null or undefined
            assertParamExists('updateSessionNumber', 'cotatoUpdateSessionNumberRequest', cotatoUpdateSessionNumberRequest)
            const localVarPath = `/v1/api/session/number`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(cotatoUpdateSessionNumberRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * SessionControllerApi - functional programming interface
 * @export
 */
export const SessionControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = SessionControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * 세션 추가하기
         * @summary Session 추가하기
         * @param {number} generationId 
         * @param {string} title 
         * @param {string} description 
         * @param {string} sessionDate 
         * @param {Array<File>} [images] 
         * @param {number} [latitude] 
         * @param {number} [longitude] 
         * @param {string} [placeName] 
         * @param {CotatoLocalTime} [attendanceDeadLine] 
         * @param {CotatoLocalTime} [lateDeadLine] 
         * @param {AddSessionItIssueEnum} [itIssue] 
         * @param {AddSessionNetworkingEnum} [networking] 
         * @param {AddSessionCsEducationEnum} [csEducation] 
         * @param {AddSessionDevTalkEnum} [devTalk] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async addSession(generationId: number, title: string, description: string, sessionDate: string, images?: Array<File>, latitude?: number, longitude?: number, placeName?: string, attendanceDeadLine?: CotatoLocalTime, lateDeadLine?: CotatoLocalTime, itIssue?: AddSessionItIssueEnum, networking?: AddSessionNetworkingEnum, csEducation?: AddSessionCsEducationEnum, devTalk?: AddSessionDevTalkEnum, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CotatoAddSessionResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.addSession(generationId, title, description, sessionDate, images, latitude, longitude, placeName, attendanceDeadLine, lateDeadLine, itIssue, networking, csEducation, devTalk, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SessionControllerApi.addSession']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 세션 수정 시 사진 추가하기, photoId 반환
         * @summary Session 수정 - 사진 추가하기
         * @param {number} sessionId 
         * @param {File} image 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async additionalSessionImage(sessionId: number, image: File, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CotatoAddSessionImageResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.additionalSessionImage(sessionId, image, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SessionControllerApi.additionalSessionImage']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 사진 삭제하기
         * @summary Session 수정 - 사진 삭제하기
         * @param {CotatoDeleteSessionImageRequest} cotatoDeleteSessionImageRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteSessionImage(cotatoDeleteSessionImageRequest: CotatoDeleteSessionImageRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteSessionImage(cotatoDeleteSessionImageRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SessionControllerApi.deleteSessionImage']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} generationId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async findAllCsOnSessionsByGenerationId(generationId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<CotatoCsEducationOnSessionNumberResponse>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.findAllCsOnSessionsByGenerationId(generationId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SessionControllerApi.findAllCsOnSessionsByGenerationId']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get Session Infos
         * @summary Session 리스트 정보 얻기
         * @param {number} generationId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async findSessionsByGenerationId(generationId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<CotatoSessionListResponse>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.findSessionsByGenerationId(generationId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SessionControllerApi.findSessionsByGenerationId']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {CotatoUpdateSessionRequest} cotatoUpdateSessionRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateSession(cotatoUpdateSessionRequest: CotatoUpdateSessionRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateSession(cotatoUpdateSessionRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SessionControllerApi.updateSession']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 세션 사진 순서 바꾸기
         * @summary Session 수정 - 사진 순서
         * @param {CotatoUpdateSessionImageOrderRequest} cotatoUpdateSessionImageOrderRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateSessionImageOrder(cotatoUpdateSessionImageOrderRequest: CotatoUpdateSessionImageOrderRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateSessionImageOrder(cotatoUpdateSessionImageOrderRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SessionControllerApi.updateSessionImageOrder']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {CotatoUpdateSessionNumberRequest} cotatoUpdateSessionNumberRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateSessionNumber(cotatoUpdateSessionNumberRequest: CotatoUpdateSessionNumberRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateSessionNumber(cotatoUpdateSessionNumberRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SessionControllerApi.updateSessionNumber']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * SessionControllerApi - factory interface
 * @export
 */
export const SessionControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = SessionControllerApiFp(configuration)
    return {
        /**
         * 세션 추가하기
         * @summary Session 추가하기
         * @param {SessionControllerApiAddSessionRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addSession(requestParameters: SessionControllerApiAddSessionRequest, options?: RawAxiosRequestConfig): AxiosPromise<CotatoAddSessionResponse> {
            return localVarFp.addSession(requestParameters.generationId, requestParameters.title, requestParameters.description, requestParameters.sessionDate, requestParameters.images, requestParameters.latitude, requestParameters.longitude, requestParameters.placeName, requestParameters.attendanceDeadLine, requestParameters.lateDeadLine, requestParameters.itIssue, requestParameters.networking, requestParameters.csEducation, requestParameters.devTalk, options).then((request) => request(axios, basePath));
        },
        /**
         * 세션 수정 시 사진 추가하기, photoId 반환
         * @summary Session 수정 - 사진 추가하기
         * @param {SessionControllerApiAdditionalSessionImageRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        additionalSessionImage(requestParameters: SessionControllerApiAdditionalSessionImageRequest, options?: RawAxiosRequestConfig): AxiosPromise<CotatoAddSessionImageResponse> {
            return localVarFp.additionalSessionImage(requestParameters.sessionId, requestParameters.image, options).then((request) => request(axios, basePath));
        },
        /**
         * 사진 삭제하기
         * @summary Session 수정 - 사진 삭제하기
         * @param {SessionControllerApiDeleteSessionImageRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteSessionImage(requestParameters: SessionControllerApiDeleteSessionImageRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deleteSessionImage(requestParameters.cotatoDeleteSessionImageRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {SessionControllerApiFindAllCsOnSessionsByGenerationIdRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        findAllCsOnSessionsByGenerationId(requestParameters: SessionControllerApiFindAllCsOnSessionsByGenerationIdRequest, options?: RawAxiosRequestConfig): AxiosPromise<Array<CotatoCsEducationOnSessionNumberResponse>> {
            return localVarFp.findAllCsOnSessionsByGenerationId(requestParameters.generationId, options).then((request) => request(axios, basePath));
        },
        /**
         * Get Session Infos
         * @summary Session 리스트 정보 얻기
         * @param {SessionControllerApiFindSessionsByGenerationIdRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        findSessionsByGenerationId(requestParameters: SessionControllerApiFindSessionsByGenerationIdRequest, options?: RawAxiosRequestConfig): AxiosPromise<Array<CotatoSessionListResponse>> {
            return localVarFp.findSessionsByGenerationId(requestParameters.generationId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {SessionControllerApiUpdateSessionRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateSession(requestParameters: SessionControllerApiUpdateSessionRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.updateSession(requestParameters.cotatoUpdateSessionRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 세션 사진 순서 바꾸기
         * @summary Session 수정 - 사진 순서
         * @param {SessionControllerApiUpdateSessionImageOrderRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateSessionImageOrder(requestParameters: SessionControllerApiUpdateSessionImageOrderRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.updateSessionImageOrder(requestParameters.cotatoUpdateSessionImageOrderRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {SessionControllerApiUpdateSessionNumberRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateSessionNumber(requestParameters: SessionControllerApiUpdateSessionNumberRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.updateSessionNumber(requestParameters.cotatoUpdateSessionNumberRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for addSession operation in SessionControllerApi.
 * @export
 * @interface SessionControllerApiAddSessionRequest
 */
export interface SessionControllerApiAddSessionRequest {
    /**
     * 
     * @type {number}
     * @memberof SessionControllerApiAddSession
     */
    readonly generationId: number

    /**
     * 
     * @type {string}
     * @memberof SessionControllerApiAddSession
     */
    readonly title: string

    /**
     * 
     * @type {string}
     * @memberof SessionControllerApiAddSession
     */
    readonly description: string

    /**
     * 
     * @type {string}
     * @memberof SessionControllerApiAddSession
     */
    readonly sessionDate: string

    /**
     * 
     * @type {Array<File>}
     * @memberof SessionControllerApiAddSession
     */
    readonly images?: Array<File>

    /**
     * 
     * @type {number}
     * @memberof SessionControllerApiAddSession
     */
    readonly latitude?: number

    /**
     * 
     * @type {number}
     * @memberof SessionControllerApiAddSession
     */
    readonly longitude?: number

    /**
     * 
     * @type {string}
     * @memberof SessionControllerApiAddSession
     */
    readonly placeName?: string

    /**
     * 
     * @type {CotatoLocalTime}
     * @memberof SessionControllerApiAddSession
     */
    readonly attendanceDeadLine?: CotatoLocalTime

    /**
     * 
     * @type {CotatoLocalTime}
     * @memberof SessionControllerApiAddSession
     */
    readonly lateDeadLine?: CotatoLocalTime

    /**
     * 
     * @type {string}
     * @memberof SessionControllerApiAddSession
     */
    readonly itIssue?: AddSessionItIssueEnum

    /**
     * 
     * @type {string}
     * @memberof SessionControllerApiAddSession
     */
    readonly networking?: AddSessionNetworkingEnum

    /**
     * 
     * @type {string}
     * @memberof SessionControllerApiAddSession
     */
    readonly csEducation?: AddSessionCsEducationEnum

    /**
     * 
     * @type {string}
     * @memberof SessionControllerApiAddSession
     */
    readonly devTalk?: AddSessionDevTalkEnum
}

/**
 * Request parameters for additionalSessionImage operation in SessionControllerApi.
 * @export
 * @interface SessionControllerApiAdditionalSessionImageRequest
 */
export interface SessionControllerApiAdditionalSessionImageRequest {
    /**
     * 
     * @type {number}
     * @memberof SessionControllerApiAdditionalSessionImage
     */
    readonly sessionId: number

    /**
     * 
     * @type {File}
     * @memberof SessionControllerApiAdditionalSessionImage
     */
    readonly image: File
}

/**
 * Request parameters for deleteSessionImage operation in SessionControllerApi.
 * @export
 * @interface SessionControllerApiDeleteSessionImageRequest
 */
export interface SessionControllerApiDeleteSessionImageRequest {
    /**
     * 
     * @type {CotatoDeleteSessionImageRequest}
     * @memberof SessionControllerApiDeleteSessionImage
     */
    readonly cotatoDeleteSessionImageRequest: CotatoDeleteSessionImageRequest
}

/**
 * Request parameters for findAllCsOnSessionsByGenerationId operation in SessionControllerApi.
 * @export
 * @interface SessionControllerApiFindAllCsOnSessionsByGenerationIdRequest
 */
export interface SessionControllerApiFindAllCsOnSessionsByGenerationIdRequest {
    /**
     * 
     * @type {number}
     * @memberof SessionControllerApiFindAllCsOnSessionsByGenerationId
     */
    readonly generationId: number
}

/**
 * Request parameters for findSessionsByGenerationId operation in SessionControllerApi.
 * @export
 * @interface SessionControllerApiFindSessionsByGenerationIdRequest
 */
export interface SessionControllerApiFindSessionsByGenerationIdRequest {
    /**
     * 
     * @type {number}
     * @memberof SessionControllerApiFindSessionsByGenerationId
     */
    readonly generationId: number
}

/**
 * Request parameters for updateSession operation in SessionControllerApi.
 * @export
 * @interface SessionControllerApiUpdateSessionRequest
 */
export interface SessionControllerApiUpdateSessionRequest {
    /**
     * 
     * @type {CotatoUpdateSessionRequest}
     * @memberof SessionControllerApiUpdateSession
     */
    readonly cotatoUpdateSessionRequest: CotatoUpdateSessionRequest
}

/**
 * Request parameters for updateSessionImageOrder operation in SessionControllerApi.
 * @export
 * @interface SessionControllerApiUpdateSessionImageOrderRequest
 */
export interface SessionControllerApiUpdateSessionImageOrderRequest {
    /**
     * 
     * @type {CotatoUpdateSessionImageOrderRequest}
     * @memberof SessionControllerApiUpdateSessionImageOrder
     */
    readonly cotatoUpdateSessionImageOrderRequest: CotatoUpdateSessionImageOrderRequest
}

/**
 * Request parameters for updateSessionNumber operation in SessionControllerApi.
 * @export
 * @interface SessionControllerApiUpdateSessionNumberRequest
 */
export interface SessionControllerApiUpdateSessionNumberRequest {
    /**
     * 
     * @type {CotatoUpdateSessionNumberRequest}
     * @memberof SessionControllerApiUpdateSessionNumber
     */
    readonly cotatoUpdateSessionNumberRequest: CotatoUpdateSessionNumberRequest
}

/**
 * SessionControllerApi - object-oriented interface
 * @export
 * @class SessionControllerApi
 * @extends {BaseAPI}
 */
export class SessionControllerApi extends BaseAPI {
    /**
     * 세션 추가하기
     * @summary Session 추가하기
     * @param {SessionControllerApiAddSessionRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SessionControllerApi
     */
    public addSession(requestParameters: SessionControllerApiAddSessionRequest, options?: RawAxiosRequestConfig) {
        return SessionControllerApiFp(this.configuration).addSession(requestParameters.generationId, requestParameters.title, requestParameters.description, requestParameters.sessionDate, requestParameters.images, requestParameters.latitude, requestParameters.longitude, requestParameters.placeName, requestParameters.attendanceDeadLine, requestParameters.lateDeadLine, requestParameters.itIssue, requestParameters.networking, requestParameters.csEducation, requestParameters.devTalk, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 세션 수정 시 사진 추가하기, photoId 반환
     * @summary Session 수정 - 사진 추가하기
     * @param {SessionControllerApiAdditionalSessionImageRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SessionControllerApi
     */
    public additionalSessionImage(requestParameters: SessionControllerApiAdditionalSessionImageRequest, options?: RawAxiosRequestConfig) {
        return SessionControllerApiFp(this.configuration).additionalSessionImage(requestParameters.sessionId, requestParameters.image, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 사진 삭제하기
     * @summary Session 수정 - 사진 삭제하기
     * @param {SessionControllerApiDeleteSessionImageRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SessionControllerApi
     */
    public deleteSessionImage(requestParameters: SessionControllerApiDeleteSessionImageRequest, options?: RawAxiosRequestConfig) {
        return SessionControllerApiFp(this.configuration).deleteSessionImage(requestParameters.cotatoDeleteSessionImageRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {SessionControllerApiFindAllCsOnSessionsByGenerationIdRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SessionControllerApi
     */
    public findAllCsOnSessionsByGenerationId(requestParameters: SessionControllerApiFindAllCsOnSessionsByGenerationIdRequest, options?: RawAxiosRequestConfig) {
        return SessionControllerApiFp(this.configuration).findAllCsOnSessionsByGenerationId(requestParameters.generationId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get Session Infos
     * @summary Session 리스트 정보 얻기
     * @param {SessionControllerApiFindSessionsByGenerationIdRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SessionControllerApi
     */
    public findSessionsByGenerationId(requestParameters: SessionControllerApiFindSessionsByGenerationIdRequest, options?: RawAxiosRequestConfig) {
        return SessionControllerApiFp(this.configuration).findSessionsByGenerationId(requestParameters.generationId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {SessionControllerApiUpdateSessionRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SessionControllerApi
     */
    public updateSession(requestParameters: SessionControllerApiUpdateSessionRequest, options?: RawAxiosRequestConfig) {
        return SessionControllerApiFp(this.configuration).updateSession(requestParameters.cotatoUpdateSessionRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 세션 사진 순서 바꾸기
     * @summary Session 수정 - 사진 순서
     * @param {SessionControllerApiUpdateSessionImageOrderRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SessionControllerApi
     */
    public updateSessionImageOrder(requestParameters: SessionControllerApiUpdateSessionImageOrderRequest, options?: RawAxiosRequestConfig) {
        return SessionControllerApiFp(this.configuration).updateSessionImageOrder(requestParameters.cotatoUpdateSessionImageOrderRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {SessionControllerApiUpdateSessionNumberRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SessionControllerApi
     */
    public updateSessionNumber(requestParameters: SessionControllerApiUpdateSessionNumberRequest, options?: RawAxiosRequestConfig) {
        return SessionControllerApiFp(this.configuration).updateSessionNumber(requestParameters.cotatoUpdateSessionNumberRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

/**
 * @export
 */
export const AddSessionItIssueEnum = {
    On: 'IT_ON',
    Off: 'IT_OFF'
} as const;
export type AddSessionItIssueEnum = typeof AddSessionItIssueEnum[keyof typeof AddSessionItIssueEnum];
/**
 * @export
 */
export const AddSessionNetworkingEnum = {
    On: 'NW_ON',
    Off: 'NW_OFF'
} as const;
export type AddSessionNetworkingEnum = typeof AddSessionNetworkingEnum[keyof typeof AddSessionNetworkingEnum];
/**
 * @export
 */
export const AddSessionCsEducationEnum = {
    On: 'CS_ON',
    Off: 'CS_OFF'
} as const;
export type AddSessionCsEducationEnum = typeof AddSessionCsEducationEnum[keyof typeof AddSessionCsEducationEnum];
/**
 * @export
 */
export const AddSessionDevTalkEnum = {
    On: 'DEVTALK_ON',
    Off: 'DEVTALK_OFF'
} as const;
export type AddSessionDevTalkEnum = typeof AddSessionDevTalkEnum[keyof typeof AddSessionDevTalkEnum];
