/* tslint:disable */
/* eslint-disable */
/**
 * CS-QUIZ 프로젝트 API 명세서
 * quiz api 명세서
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime.js';
import type {
  CotatoApplyMemberInfoResponse,
  CotatoMemberApproveRequest,
  CotatoMemberEnrollInfoResponse,
  CotatoMemberRejectRequest,
  CotatoUpdateActiveMemberRoleRequest,
  CotatoUpdateActiveMemberToOldMemberRequest,
  CotatoUpdateOldMemberRoleRequest,
} from '../models/index.js';
import {
    CotatoApplyMemberInfoResponseFromJSON,
    CotatoApplyMemberInfoResponseToJSON,
    CotatoMemberApproveRequestFromJSON,
    CotatoMemberApproveRequestToJSON,
    CotatoMemberEnrollInfoResponseFromJSON,
    CotatoMemberEnrollInfoResponseToJSON,
    CotatoMemberRejectRequestFromJSON,
    CotatoMemberRejectRequestToJSON,
    CotatoUpdateActiveMemberRoleRequestFromJSON,
    CotatoUpdateActiveMemberRoleRequestToJSON,
    CotatoUpdateActiveMemberToOldMemberRequestFromJSON,
    CotatoUpdateActiveMemberToOldMemberRequestToJSON,
    CotatoUpdateOldMemberRoleRequestFromJSON,
    CotatoUpdateOldMemberRoleRequestToJSON,
} from '../models/index.js';

export interface ApproveApplicantRequest {
    cotatoMemberApproveRequest: CotatoMemberApproveRequest;
}

export interface ReapproveApplicantRequest {
    cotatoMemberApproveRequest: CotatoMemberApproveRequest;
}

export interface RejectApplicantRequest {
    cotatoMemberRejectRequest: CotatoMemberRejectRequest;
}

export interface UpdateActiveMemberRoleRequest {
    cotatoUpdateActiveMemberRoleRequest: CotatoUpdateActiveMemberRoleRequest;
}

export interface UpdateActiveMembersToOldMembersRequest {
    cotatoUpdateActiveMemberToOldMemberRequest: CotatoUpdateActiveMemberToOldMemberRequest;
}

export interface UpdateOldMemberToActiveGenerationRequest {
    cotatoUpdateOldMemberRoleRequest: CotatoUpdateOldMemberRoleRequest;
}

/**
 * 
 */
export class AdminControllerApi extends runtime.BaseAPI {

    /**
     */
    async approveApplicantRaw(requestParameters: ApproveApplicantRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['cotatoMemberApproveRequest'] == null) {
            throw new runtime.RequiredError(
                'cotatoMemberApproveRequest',
                'Required parameter "cotatoMemberApproveRequest" was null or undefined when calling approveApplicant().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/api/admin/approve`,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: CotatoMemberApproveRequestToJSON(requestParameters['cotatoMemberApproveRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async approveApplicant(requestParameters: ApproveApplicantRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.approveApplicantRaw(requestParameters, initOverrides);
    }

    /**
     */
    async findApplicantListRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<CotatoApplyMemberInfoResponse>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/api/admin/applicants`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(CotatoApplyMemberInfoResponseFromJSON));
    }

    /**
     */
    async findApplicantList(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<CotatoApplyMemberInfoResponse>> {
        const response = await this.findApplicantListRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async findCurrentActiveMembersRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<CotatoMemberEnrollInfoResponse>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/api/admin/active-members`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(CotatoMemberEnrollInfoResponseFromJSON));
    }

    /**
     */
    async findCurrentActiveMembers(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<CotatoMemberEnrollInfoResponse>> {
        const response = await this.findCurrentActiveMembersRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async findOldMembersRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<CotatoMemberEnrollInfoResponse>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/api/admin/old-members`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(CotatoMemberEnrollInfoResponseFromJSON));
    }

    /**
     */
    async findOldMembers(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<CotatoMemberEnrollInfoResponse>> {
        const response = await this.findOldMembersRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async findRejectApplicantListRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<CotatoApplyMemberInfoResponse>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/api/admin/reject-applicants`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(CotatoApplyMemberInfoResponseFromJSON));
    }

    /**
     */
    async findRejectApplicantList(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<CotatoApplyMemberInfoResponse>> {
        const response = await this.findRejectApplicantListRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async reapproveApplicantRaw(requestParameters: ReapproveApplicantRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['cotatoMemberApproveRequest'] == null) {
            throw new runtime.RequiredError(
                'cotatoMemberApproveRequest',
                'Required parameter "cotatoMemberApproveRequest" was null or undefined when calling reapproveApplicant().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/api/admin/reapprove`,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: CotatoMemberApproveRequestToJSON(requestParameters['cotatoMemberApproveRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async reapproveApplicant(requestParameters: ReapproveApplicantRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.reapproveApplicantRaw(requestParameters, initOverrides);
    }

    /**
     */
    async rejectApplicantRaw(requestParameters: RejectApplicantRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['cotatoMemberRejectRequest'] == null) {
            throw new runtime.RequiredError(
                'cotatoMemberRejectRequest',
                'Required parameter "cotatoMemberRejectRequest" was null or undefined when calling rejectApplicant().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/api/admin/reject`,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: CotatoMemberRejectRequestToJSON(requestParameters['cotatoMemberRejectRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async rejectApplicant(requestParameters: RejectApplicantRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.rejectApplicantRaw(requestParameters, initOverrides);
    }

    /**
     */
    async updateActiveMemberRoleRaw(requestParameters: UpdateActiveMemberRoleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['cotatoUpdateActiveMemberRoleRequest'] == null) {
            throw new runtime.RequiredError(
                'cotatoUpdateActiveMemberRoleRequest',
                'Required parameter "cotatoUpdateActiveMemberRoleRequest" was null or undefined when calling updateActiveMemberRole().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/api/admin/active-members/role`,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: CotatoUpdateActiveMemberRoleRequestToJSON(requestParameters['cotatoUpdateActiveMemberRoleRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async updateActiveMemberRole(requestParameters: UpdateActiveMemberRoleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.updateActiveMemberRoleRaw(requestParameters, initOverrides);
    }

    /**
     */
    async updateActiveMembersToOldMembersRaw(requestParameters: UpdateActiveMembersToOldMembersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['cotatoUpdateActiveMemberToOldMemberRequest'] == null) {
            throw new runtime.RequiredError(
                'cotatoUpdateActiveMemberToOldMemberRequest',
                'Required parameter "cotatoUpdateActiveMemberToOldMemberRequest" was null or undefined when calling updateActiveMembersToOldMembers().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/api/admin/active-members/to-old-members`,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: CotatoUpdateActiveMemberToOldMemberRequestToJSON(requestParameters['cotatoUpdateActiveMemberToOldMemberRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async updateActiveMembersToOldMembers(requestParameters: UpdateActiveMembersToOldMembersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.updateActiveMembersToOldMembersRaw(requestParameters, initOverrides);
    }

    /**
     */
    async updateOldMemberToActiveGenerationRaw(requestParameters: UpdateOldMemberToActiveGenerationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['cotatoUpdateOldMemberRoleRequest'] == null) {
            throw new runtime.RequiredError(
                'cotatoUpdateOldMemberRoleRequest',
                'Required parameter "cotatoUpdateOldMemberRoleRequest" was null or undefined when calling updateOldMemberToActiveGeneration().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/api/admin/old-members/role`,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: CotatoUpdateOldMemberRoleRequestToJSON(requestParameters['cotatoUpdateOldMemberRoleRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async updateOldMemberToActiveGeneration(requestParameters: UpdateOldMemberToActiveGenerationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.updateOldMemberToActiveGenerationRaw(requestParameters, initOverrides);
    }

}
