/* tslint:disable */
/* eslint-disable */
/**
 * COTATO 프로젝트 API 명세서
 * api 명세서
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface CotatoDeleteGenerationMemberRequest
 */
export interface CotatoDeleteGenerationMemberRequest {
    /**
     * 
     * @type {Array<number>}
     * @memberof CotatoDeleteGenerationMemberRequest
     */
    generationMemberIds: Array<number>;
}

/**
 * Check if a given object implements the CotatoDeleteGenerationMemberRequest interface.
 */
export function instanceOfCotatoDeleteGenerationMemberRequest(value: object): value is CotatoDeleteGenerationMemberRequest {
    if (!('generationMemberIds' in value) || value['generationMemberIds'] === undefined) return false;
    return true;
}

export function CotatoDeleteGenerationMemberRequestFromJSON(json: any): CotatoDeleteGenerationMemberRequest {
    return CotatoDeleteGenerationMemberRequestFromJSONTyped(json, false);
}

export function CotatoDeleteGenerationMemberRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CotatoDeleteGenerationMemberRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'generationMemberIds': json['generationMemberIds'],
    };
}

export function CotatoDeleteGenerationMemberRequestToJSON(value?: CotatoDeleteGenerationMemberRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'generationMemberIds': value['generationMemberIds'],
    };
}

