/* tslint:disable */
/* eslint-disable */
/**
 * COTATO 프로젝트 API 명세서
 * api 명세서
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface CotatoEducationCloseRequest
 */
export interface CotatoEducationCloseRequest {
    /**
     * 
     * @type {number}
     * @memberof CotatoEducationCloseRequest
     */
    educationId: number;
}

/**
 * Check if a given object implements the CotatoEducationCloseRequest interface.
 */
export function instanceOfCotatoEducationCloseRequest(value: object): value is CotatoEducationCloseRequest {
    if (!('educationId' in value) || value['educationId'] === undefined) return false;
    return true;
}

export function CotatoEducationCloseRequestFromJSON(json: any): CotatoEducationCloseRequest {
    return CotatoEducationCloseRequestFromJSONTyped(json, false);
}

export function CotatoEducationCloseRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CotatoEducationCloseRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'educationId': json['educationId'],
    };
}

export function CotatoEducationCloseRequestToJSON(value?: CotatoEducationCloseRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'educationId': value['educationId'],
    };
}

