/* tslint:disable */
/* eslint-disable */
/**
 * CS-QUIZ 프로젝트 API 명세서
 * quiz api 명세서
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface CotatoSessionListImageInfoResponse
 */
export interface CotatoSessionListImageInfoResponse {
    /**
     * 
     * @type {number}
     * @memberof CotatoSessionListImageInfoResponse
     */
    imageId?: number;
    /**
     * 
     * @type {string}
     * @memberof CotatoSessionListImageInfoResponse
     */
    imageUrl?: string;
    /**
     * 
     * @type {number}
     * @memberof CotatoSessionListImageInfoResponse
     */
    order?: number;
}

/**
 * Check if a given object implements the CotatoSessionListImageInfoResponse interface.
 */
export function instanceOfCotatoSessionListImageInfoResponse(value: object): value is CotatoSessionListImageInfoResponse {
    return true;
}

export function CotatoSessionListImageInfoResponseFromJSON(json: any): CotatoSessionListImageInfoResponse {
    return CotatoSessionListImageInfoResponseFromJSONTyped(json, false);
}

export function CotatoSessionListImageInfoResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CotatoSessionListImageInfoResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'imageId': json['imageId'] == null ? undefined : json['imageId'],
        'imageUrl': json['imageUrl'] == null ? undefined : json['imageUrl'],
        'order': json['order'] == null ? undefined : json['order'],
    };
}

export function CotatoSessionListImageInfoResponseToJSON(value?: CotatoSessionListImageInfoResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'imageId': value['imageId'],
        'imageUrl': value['imageUrl'],
        'order': value['order'],
    };
}

