/* tslint:disable */
/* eslint-disable */
/**
 * COTATO 프로젝트 API 명세서
 * api 명세서
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface CotatoCheckPolicyRequest
 */
export interface CotatoCheckPolicyRequest {
    /**
     * 체크할 정책 PK
     * @type {number}
     * @memberof CotatoCheckPolicyRequest
     */
    policyId: number;
    /**
     * 정책 동의 여부
     * @type {boolean}
     * @memberof CotatoCheckPolicyRequest
     */
    isChecked: boolean;
}

/**
 * Check if a given object implements the CotatoCheckPolicyRequest interface.
 */
export function instanceOfCotatoCheckPolicyRequest(value: object): value is CotatoCheckPolicyRequest {
    if (!('policyId' in value) || value['policyId'] === undefined) return false;
    if (!('isChecked' in value) || value['isChecked'] === undefined) return false;
    return true;
}

export function CotatoCheckPolicyRequestFromJSON(json: any): CotatoCheckPolicyRequest {
    return CotatoCheckPolicyRequestFromJSONTyped(json, false);
}

export function CotatoCheckPolicyRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CotatoCheckPolicyRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'policyId': json['policyId'],
        'isChecked': json['isChecked'],
    };
}

export function CotatoCheckPolicyRequestToJSON(value?: CotatoCheckPolicyRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'policyId': value['policyId'],
        'isChecked': value['isChecked'],
    };
}

