/* tslint:disable */
/* eslint-disable */
/**
 * CS-QUIZ 프로젝트 API 명세서
 * quiz api 명세서
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { CotatoChoiceResponse } from './CotatoChoiceResponse.js';
import {
    CotatoChoiceResponseFromJSON,
    CotatoChoiceResponseFromJSONTyped,
    CotatoChoiceResponseToJSON,
} from './CotatoChoiceResponse.js';

/**
 * 
 * @export
 * @interface CotatoMultipleQuizResponse
 */
export interface CotatoMultipleQuizResponse {
    /**
     * 
     * @type {number}
     * @memberof CotatoMultipleQuizResponse
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof CotatoMultipleQuizResponse
     */
    number?: number;
    /**
     * 
     * @type {string}
     * @memberof CotatoMultipleQuizResponse
     */
    question?: string;
    /**
     * 
     * @type {string}
     * @memberof CotatoMultipleQuizResponse
     */
    image?: string;
    /**
     * 
     * @type {Array<CotatoChoiceResponse>}
     * @memberof CotatoMultipleQuizResponse
     */
    choices?: Array<CotatoChoiceResponse>;
}

/**
 * Check if a given object implements the CotatoMultipleQuizResponse interface.
 */
export function instanceOfCotatoMultipleQuizResponse(value: object): value is CotatoMultipleQuizResponse {
    return true;
}

export function CotatoMultipleQuizResponseFromJSON(json: any): CotatoMultipleQuizResponse {
    return CotatoMultipleQuizResponseFromJSONTyped(json, false);
}

export function CotatoMultipleQuizResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CotatoMultipleQuizResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'number': json['number'] == null ? undefined : json['number'],
        'question': json['question'] == null ? undefined : json['question'],
        'image': json['image'] == null ? undefined : json['image'],
        'choices': json['choices'] == null ? undefined : ((json['choices'] as Array<any>).map(CotatoChoiceResponseFromJSON)),
    };
}

export function CotatoMultipleQuizResponseToJSON(value?: CotatoMultipleQuizResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'number': value['number'],
        'question': value['question'],
        'image': value['image'],
        'choices': value['choices'] == null ? undefined : ((value['choices'] as Array<any>).map(CotatoChoiceResponseToJSON)),
    };
}

