/* tslint:disable */
/* eslint-disable */
/**
 * CS-QUIZ 프로젝트 API 명세서
 * quiz api 명세서
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface CotatoQuizInfoInCsQuizResponse
 */
export interface CotatoQuizInfoInCsQuizResponse {
    /**
     * 
     * @type {number}
     * @memberof CotatoQuizInfoInCsQuizResponse
     */
    quizId?: number;
    /**
     * 
     * @type {string}
     * @memberof CotatoQuizInfoInCsQuizResponse
     */
    quizType?: CotatoQuizInfoInCsQuizResponseQuizTypeEnum;
    /**
     * 
     * @type {number}
     * @memberof CotatoQuizInfoInCsQuizResponse
     */
    quizNumber?: number;
    /**
     * 
     * @type {string}
     * @memberof CotatoQuizInfoInCsQuizResponse
     */
    question?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof CotatoQuizInfoInCsQuizResponse
     */
    answer?: Array<string>;
}


/**
 * @export
 */
export const CotatoQuizInfoInCsQuizResponseQuizTypeEnum = {
    MultipleQuiz: 'MULTIPLE_QUIZ',
    ShortQuiz: 'SHORT_QUIZ'
} as const;
export type CotatoQuizInfoInCsQuizResponseQuizTypeEnum = typeof CotatoQuizInfoInCsQuizResponseQuizTypeEnum[keyof typeof CotatoQuizInfoInCsQuizResponseQuizTypeEnum];


/**
 * Check if a given object implements the CotatoQuizInfoInCsQuizResponse interface.
 */
export function instanceOfCotatoQuizInfoInCsQuizResponse(value: object): value is CotatoQuizInfoInCsQuizResponse {
    return true;
}

export function CotatoQuizInfoInCsQuizResponseFromJSON(json: any): CotatoQuizInfoInCsQuizResponse {
    return CotatoQuizInfoInCsQuizResponseFromJSONTyped(json, false);
}

export function CotatoQuizInfoInCsQuizResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CotatoQuizInfoInCsQuizResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'quizId': json['quizId'] == null ? undefined : json['quizId'],
        'quizType': json['quizType'] == null ? undefined : json['quizType'],
        'quizNumber': json['quizNumber'] == null ? undefined : json['quizNumber'],
        'question': json['question'] == null ? undefined : json['question'],
        'answer': json['answer'] == null ? undefined : json['answer'],
    };
}

export function CotatoQuizInfoInCsQuizResponseToJSON(value?: CotatoQuizInfoInCsQuizResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'quizId': value['quizId'],
        'quizType': value['quizType'],
        'quizNumber': value['quizNumber'],
        'question': value['question'],
        'answer': value['answer'],
    };
}

