/* tslint:disable */
/* eslint-disable */
/**
 * CS-QUIZ 프로젝트 API 명세서
 * quiz api 명세서
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface CotatoMemberMyPageInfoResponse
 */
export interface CotatoMemberMyPageInfoResponse {
    /**
     * 
     * @type {number}
     * @memberof CotatoMemberMyPageInfoResponse
     */
    memberId?: number;
    /**
     * 
     * @type {string}
     * @memberof CotatoMemberMyPageInfoResponse
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof CotatoMemberMyPageInfoResponse
     */
    name?: string;
    /**
     * 
     * @type {number}
     * @memberof CotatoMemberMyPageInfoResponse
     */
    generationNumber?: number;
    /**
     * 
     * @type {string}
     * @memberof CotatoMemberMyPageInfoResponse
     */
    position?: CotatoMemberMyPageInfoResponsePositionEnum;
    /**
     * 
     * @type {string}
     * @memberof CotatoMemberMyPageInfoResponse
     */
    phoneNumber?: string;
    /**
     * 
     * @type {string}
     * @memberof CotatoMemberMyPageInfoResponse
     */
    profileImage?: string;
}


/**
 * @export
 */
export const CotatoMemberMyPageInfoResponsePositionEnum = {
    None: 'NONE',
    Be: 'BE',
    Fe: 'FE',
    Design: 'DESIGN',
    Pm: 'PM'
} as const;
export type CotatoMemberMyPageInfoResponsePositionEnum = typeof CotatoMemberMyPageInfoResponsePositionEnum[keyof typeof CotatoMemberMyPageInfoResponsePositionEnum];


/**
 * Check if a given object implements the CotatoMemberMyPageInfoResponse interface.
 */
export function instanceOfCotatoMemberMyPageInfoResponse(value: object): value is CotatoMemberMyPageInfoResponse {
    return true;
}

export function CotatoMemberMyPageInfoResponseFromJSON(json: any): CotatoMemberMyPageInfoResponse {
    return CotatoMemberMyPageInfoResponseFromJSONTyped(json, false);
}

export function CotatoMemberMyPageInfoResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CotatoMemberMyPageInfoResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'memberId': json['memberId'] == null ? undefined : json['memberId'],
        'email': json['email'] == null ? undefined : json['email'],
        'name': json['name'] == null ? undefined : json['name'],
        'generationNumber': json['generationNumber'] == null ? undefined : json['generationNumber'],
        'position': json['position'] == null ? undefined : json['position'],
        'phoneNumber': json['phoneNumber'] == null ? undefined : json['phoneNumber'],
        'profileImage': json['profileImage'] == null ? undefined : json['profileImage'],
    };
}

export function CotatoMemberMyPageInfoResponseToJSON(value?: CotatoMemberMyPageInfoResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'memberId': value['memberId'],
        'email': value['email'],
        'name': value['name'],
        'generationNumber': value['generationNumber'],
        'position': value['position'],
        'phoneNumber': value['phoneNumber'],
        'profileImage': value['profileImage'],
    };
}

