/* tslint:disable */
/* eslint-disable */
/**
 * CS-QUIZ 프로젝트 API 명세서
 * quiz api 명세서
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface CotatoKingMemberInfo
 */
export interface CotatoKingMemberInfo {
    /**
     * 
     * @type {number}
     * @memberof CotatoKingMemberInfo
     */
    memberId?: number;
    /**
     * 
     * @type {string}
     * @memberof CotatoKingMemberInfo
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof CotatoKingMemberInfo
     */
    backFourNumber?: string;
}

/**
 * Check if a given object implements the CotatoKingMemberInfo interface.
 */
export function instanceOfCotatoKingMemberInfo(value: object): value is CotatoKingMemberInfo {
    return true;
}

export function CotatoKingMemberInfoFromJSON(json: any): CotatoKingMemberInfo {
    return CotatoKingMemberInfoFromJSONTyped(json, false);
}

export function CotatoKingMemberInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CotatoKingMemberInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'memberId': json['memberId'] == null ? undefined : json['memberId'],
        'name': json['name'] == null ? undefined : json['name'],
        'backFourNumber': json['backFourNumber'] == null ? undefined : json['backFourNumber'],
    };
}

export function CotatoKingMemberInfoToJSON(value?: CotatoKingMemberInfo | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'memberId': value['memberId'],
        'name': value['name'],
        'backFourNumber': value['backFourNumber'],
    };
}

