/* tslint:disable */
/* eslint-disable */
/**
 * CS-QUIZ 프로젝트 API 명세서
 * quiz api 명세서
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface CotatoProjectImageInfoResponse
 */
export interface CotatoProjectImageInfoResponse {
    /**
     * 
     * @type {number}
     * @memberof CotatoProjectImageInfoResponse
     */
    imageId?: number;
    /**
     * 
     * @type {string}
     * @memberof CotatoProjectImageInfoResponse
     */
    imageUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof CotatoProjectImageInfoResponse
     */
    projectImageType?: CotatoProjectImageInfoResponseProjectImageTypeEnum;
}


/**
 * @export
 */
export const CotatoProjectImageInfoResponseProjectImageTypeEnum = {
    Logo: 'LOGO',
    Thumbnail: 'THUMBNAIL',
    Detail: 'DETAIL'
} as const;
export type CotatoProjectImageInfoResponseProjectImageTypeEnum = typeof CotatoProjectImageInfoResponseProjectImageTypeEnum[keyof typeof CotatoProjectImageInfoResponseProjectImageTypeEnum];


/**
 * Check if a given object implements the CotatoProjectImageInfoResponse interface.
 */
export function instanceOfCotatoProjectImageInfoResponse(value: object): value is CotatoProjectImageInfoResponse {
    return true;
}

export function CotatoProjectImageInfoResponseFromJSON(json: any): CotatoProjectImageInfoResponse {
    return CotatoProjectImageInfoResponseFromJSONTyped(json, false);
}

export function CotatoProjectImageInfoResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CotatoProjectImageInfoResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'imageId': json['imageId'] == null ? undefined : json['imageId'],
        'imageUrl': json['imageUrl'] == null ? undefined : json['imageUrl'],
        'projectImageType': json['projectImageType'] == null ? undefined : json['projectImageType'],
    };
}

export function CotatoProjectImageInfoResponseToJSON(value?: CotatoProjectImageInfoResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'imageId': value['imageId'],
        'imageUrl': value['imageUrl'],
        'projectImageType': value['projectImageType'],
    };
}

