/* tslint:disable */
/* eslint-disable */
/**
 * COTATO 프로젝트 API 명세서
 * api 명세서
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface CotatoRequestNotificationRequest
 */
export interface CotatoRequestNotificationRequest {
    /**
     * 
     * @type {number}
     * @memberof CotatoRequestNotificationRequest
     */
    generationNumber: number;
}

/**
 * Check if a given object implements the CotatoRequestNotificationRequest interface.
 */
export function instanceOfCotatoRequestNotificationRequest(value: object): value is CotatoRequestNotificationRequest {
    if (!('generationNumber' in value) || value['generationNumber'] === undefined) return false;
    return true;
}

export function CotatoRequestNotificationRequestFromJSON(json: any): CotatoRequestNotificationRequest {
    return CotatoRequestNotificationRequestFromJSONTyped(json, false);
}

export function CotatoRequestNotificationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CotatoRequestNotificationRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'generationNumber': json['generationNumber'],
    };
}

export function CotatoRequestNotificationRequestToJSON(value?: CotatoRequestNotificationRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'generationNumber': value['generationNumber'],
    };
}

