/* tslint:disable */
/* eslint-disable */
/**
 * COTATO 프로젝트 API 명세서
 * api 명세서
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { CotatoCheckPolicyRequest } from './CotatoCheckPolicyRequest.js';
import {
    CotatoCheckPolicyRequestFromJSON,
    CotatoCheckPolicyRequestFromJSONTyped,
    CotatoCheckPolicyRequestToJSON,
} from './CotatoCheckPolicyRequest.js';

/**
 * 
 * @export
 * @interface CotatoCheckMemberPoliciesRequest
 */
export interface CotatoCheckMemberPoliciesRequest {
    /**
     * 
     * @type {Array<CotatoCheckPolicyRequest>}
     * @memberof CotatoCheckMemberPoliciesRequest
     */
    policies: Array<CotatoCheckPolicyRequest>;
}

/**
 * Check if a given object implements the CotatoCheckMemberPoliciesRequest interface.
 */
export function instanceOfCotatoCheckMemberPoliciesRequest(value: object): value is CotatoCheckMemberPoliciesRequest {
    if (!('policies' in value) || value['policies'] === undefined) return false;
    return true;
}

export function CotatoCheckMemberPoliciesRequestFromJSON(json: any): CotatoCheckMemberPoliciesRequest {
    return CotatoCheckMemberPoliciesRequestFromJSONTyped(json, false);
}

export function CotatoCheckMemberPoliciesRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CotatoCheckMemberPoliciesRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'policies': ((json['policies'] as Array<any>).map(CotatoCheckPolicyRequestFromJSON)),
    };
}

export function CotatoCheckMemberPoliciesRequestToJSON(value?: CotatoCheckMemberPoliciesRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'policies': ((value['policies'] as Array<any>).map(CotatoCheckPolicyRequestToJSON)),
    };
}

