/* tslint:disable */
/* eslint-disable */
/**
 * COTATO 프로젝트 API 명세서
 * api 명세서
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { CotatoAddableMemberInfo } from './CotatoAddableMemberInfo.js';
import {
    CotatoAddableMemberInfoFromJSON,
    CotatoAddableMemberInfoFromJSONTyped,
    CotatoAddableMemberInfoToJSON,
} from './CotatoAddableMemberInfo.js';

/**
 * 
 * @export
 * @interface CotatoAddableMembersResponse
 */
export interface CotatoAddableMembersResponse {
    /**
     * 
     * @type {Array<CotatoAddableMemberInfo>}
     * @memberof CotatoAddableMembersResponse
     */
    memberInfos?: Array<CotatoAddableMemberInfo>;
}

/**
 * Check if a given object implements the CotatoAddableMembersResponse interface.
 */
export function instanceOfCotatoAddableMembersResponse(value: object): value is CotatoAddableMembersResponse {
    return true;
}

export function CotatoAddableMembersResponseFromJSON(json: any): CotatoAddableMembersResponse {
    return CotatoAddableMembersResponseFromJSONTyped(json, false);
}

export function CotatoAddableMembersResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CotatoAddableMembersResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'memberInfos': json['memberInfos'] == null ? undefined : ((json['memberInfos'] as Array<any>).map(CotatoAddableMemberInfoFromJSON)),
    };
}

export function CotatoAddableMembersResponseToJSON(value?: CotatoAddableMembersResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'memberInfos': value['memberInfos'] == null ? undefined : ((value['memberInfos'] as Array<any>).map(CotatoAddableMemberInfoToJSON)),
    };
}

