/* tslint:disable */
/* eslint-disable */
/**
 * CS-QUIZ 프로젝트 API 명세서
 * quiz api 명세서
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface CotatoMemberRejectRequest
 */
export interface CotatoMemberRejectRequest {
    /**
     * 
     * @type {number}
     * @memberof CotatoMemberRejectRequest
     */
    memberId: number;
}

/**
 * Check if a given object implements the CotatoMemberRejectRequest interface.
 */
export function instanceOfCotatoMemberRejectRequest(value: object): value is CotatoMemberRejectRequest {
    if (!('memberId' in value) || value['memberId'] === undefined) return false;
    return true;
}

export function CotatoMemberRejectRequestFromJSON(json: any): CotatoMemberRejectRequest {
    return CotatoMemberRejectRequestFromJSONTyped(json, false);
}

export function CotatoMemberRejectRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CotatoMemberRejectRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'memberId': json['memberId'],
    };
}

export function CotatoMemberRejectRequestToJSON(value?: CotatoMemberRejectRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'memberId': value['memberId'],
    };
}

