/* tslint:disable */
/* eslint-disable */
/**
 * COTATO 프로젝트 API 명세서
 * api 명세서
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface CotatoSendEmailRequest
 */
export interface CotatoSendEmailRequest {
    /**
     * 
     * @type {string}
     * @memberof CotatoSendEmailRequest
     */
    email: string;
}

/**
 * Check if a given object implements the CotatoSendEmailRequest interface.
 */
export function instanceOfCotatoSendEmailRequest(value: object): value is CotatoSendEmailRequest {
    if (!('email' in value) || value['email'] === undefined) return false;
    return true;
}

export function CotatoSendEmailRequestFromJSON(json: any): CotatoSendEmailRequest {
    return CotatoSendEmailRequestFromJSONTyped(json, false);
}

export function CotatoSendEmailRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CotatoSendEmailRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
    };
}

export function CotatoSendEmailRequestToJSON(value?: CotatoSendEmailRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'email': value['email'],
    };
}

