/* tslint:disable */
/* eslint-disable */
/**
 * COTATO 프로젝트 API 명세서
 * api 명세서
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface CotatoCreateEducationRequest
 */
export interface CotatoCreateEducationRequest {
    /**
     * 
     * @type {string}
     * @memberof CotatoCreateEducationRequest
     */
    subject: string;
    /**
     * 
     * @type {number}
     * @memberof CotatoCreateEducationRequest
     */
    generationId: number;
    /**
     * 
     * @type {number}
     * @memberof CotatoCreateEducationRequest
     */
    educationNumber: number;
}

/**
 * Check if a given object implements the CotatoCreateEducationRequest interface.
 */
export function instanceOfCotatoCreateEducationRequest(value: object): value is CotatoCreateEducationRequest {
    if (!('subject' in value) || value['subject'] === undefined) return false;
    if (!('generationId' in value) || value['generationId'] === undefined) return false;
    if (!('educationNumber' in value) || value['educationNumber'] === undefined) return false;
    return true;
}

export function CotatoCreateEducationRequestFromJSON(json: any): CotatoCreateEducationRequest {
    return CotatoCreateEducationRequestFromJSONTyped(json, false);
}

export function CotatoCreateEducationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CotatoCreateEducationRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'subject': json['subject'],
        'generationId': json['generationId'],
        'educationNumber': json['educationNumber'],
    };
}

export function CotatoCreateEducationRequestToJSON(value?: CotatoCreateEducationRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'subject': value['subject'],
        'generationId': value['generationId'],
        'educationNumber': value['educationNumber'],
    };
}

