/* tslint:disable */
/* eslint-disable */
/**
 * COTATO 프로젝트 API 명세서
 * api 명세서
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 사용자 요청 위치
 * @export
 * @interface CotatoLocation
 */
export interface CotatoLocation {
    /**
     * 
     * @type {number}
     * @memberof CotatoLocation
     */
    latitude?: number;
    /**
     * 
     * @type {number}
     * @memberof CotatoLocation
     */
    longitude?: number;
}

/**
 * Check if a given object implements the CotatoLocation interface.
 */
export function instanceOfCotatoLocation(value: object): value is CotatoLocation {
    return true;
}

export function CotatoLocationFromJSON(json: any): CotatoLocation {
    return CotatoLocationFromJSONTyped(json, false);
}

export function CotatoLocationFromJSONTyped(json: any, ignoreDiscriminator: boolean): CotatoLocation {
    if (json == null) {
        return json;
    }
    return {
        
        'latitude': json['latitude'] == null ? undefined : json['latitude'],
        'longitude': json['longitude'] == null ? undefined : json['longitude'],
    };
}

export function CotatoLocationToJSON(value?: CotatoLocation | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'latitude': value['latitude'],
        'longitude': value['longitude'],
    };
}

