/* tslint:disable */
/* eslint-disable */
/**
 * CS-QUIZ 프로젝트 API 명세서
 * quiz api 명세서
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface CotatoCreateEducationRequest
 */
export interface CotatoCreateEducationRequest {
    /**
     * 
     * @type {string}
     * @memberof CotatoCreateEducationRequest
     */
    subject: string;
    /**
     * 
     * @type {number}
     * @memberof CotatoCreateEducationRequest
     */
    sessionId: number;
    /**
     * 
     * @type {number}
     * @memberof CotatoCreateEducationRequest
     */
    educationNum: number;
}

/**
 * Check if a given object implements the CotatoCreateEducationRequest interface.
 */
export function instanceOfCotatoCreateEducationRequest(value: object): value is CotatoCreateEducationRequest {
    if (!('subject' in value) || value['subject'] === undefined) return false;
    if (!('sessionId' in value) || value['sessionId'] === undefined) return false;
    if (!('educationNum' in value) || value['educationNum'] === undefined) return false;
    return true;
}

export function CotatoCreateEducationRequestFromJSON(json: any): CotatoCreateEducationRequest {
    return CotatoCreateEducationRequestFromJSONTyped(json, false);
}

export function CotatoCreateEducationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CotatoCreateEducationRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'subject': json['subject'],
        'sessionId': json['sessionId'],
        'educationNum': json['educationNum'],
    };
}

export function CotatoCreateEducationRequestToJSON(value?: CotatoCreateEducationRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'subject': value['subject'],
        'sessionId': value['sessionId'],
        'educationNum': value['educationNum'],
    };
}

